
########### Program parameters ############
inputs:
  # The directory containing the genomes of interest 
  # input_directory: data/assemblies_gzip
  # input_directory: /90daydata/shared/dbradshaw_to_pvillanueva/recheck/assemblies_gzip
  input_directory: data/query_genomes

  # A run name to organize the outputs under. All pipeline outputs will be stored in
  # outputs/<run_name>
  run_name: test_run

bakta:

  # These are the light/full paths to the databases used by Bakta
  # The light_db path should end in db-light
  light_db: /project/fsepru/paul.villanueva/databases/bakta_dbs/db-light

  # This path should end in db
  full_db: /project/fsepru/paul.villanueva/databases/bakta_dbs/db

blast:

  # The BLAST database used to search for pESI-like contigs.
  # You don't need to change this value for basic uses of the pipeline.
  infantis_pesi_genome_db: resources/dbs/complete_infantis_chrom_and_pESI_db/complete_infantis_chrom_and_pESI.fasta

panaroo:

  # WORK IN PROGRESS
  pesi_cluster_pangenome: TO_BE_IMPLEMENTED

metrics:

  # Location of the checkm2 diamond database. It should end in .dmnd. 
  # WORK IN PROGRESS
  checkm2_database: /project/fsepru/paul.villanueva/databases/CheckM2_database/uniref100.KO.1.dmnd

references:

  # An annotated Salmonella Infantis pESI plasmid
  # You don't need to change this value for basic uses of the pipeline.
  annotated_pesi: resources/CP052828.gbk
